default:
  module: "src.client.agents.FastChatAgent"
  parameters:
    name: "FastChat"
    controller_address: "http://localhost:21001"
    max_new_tokens: 512
    temperature: 0

vicuna-33b:
  parameters:
    model_name: "vicuna-33b-v1.3"

wizard-30b:
  parameters:
    model_name: "WizardLM-30B-V1.0-merged"

vicuna-13b:
  parameters:
    model_name: "vicuna-13b-v1.5"

vicuna-7b:
  parameters:
    model_name: "vicuna-7b-v1.5"

meta-llama/Meta-Llama-3-8B-Instruct:
  parameters: 
    model_name: "Meta-Llama-3-8B-Instruct"

mistralai/Mixtral-8x7B-Instruct-v0.1:
  parameters: 
    model_name: "Mixtral-8x7B-Instruct-v0.1"

mistralai/Mixtral-8x22B-v0.1:
  parameters: 
    model_name: "Mixtral-8x22B-v0.1"
